# Generated by Django 3.2 on 2022-12-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='client',
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='credit.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='credit',
            name='account',
        ),
        migrations.AddField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credit.account'),
            preserve_default=False,
        ),
    ]
